### ISSUE TITLE
Add Age data report

### ISSUE THREAD

**Issue by pedrocruzio** [marcmaceira/covid-19-pr-api#1]
Great work! I think it would very useful to include more data that is being published like the distribution of ages in the reported cases.

Feel free to grab our CSV here:

https://github.com/Code4PuertoRico/covid19-pr-api/blob/master/data/PuertoRicoTaskForce/4-10-2020/CSV/edades.csv

(Note: We are stilling working on improving our OCR pipeline for the reports so there may be errors)

**Comment by marcmaceira** [comment]
@pedrocruzio Thanks! Will do. Also, you guys are doing amazing work. Today I'll be adding data I've gathered on testing sites. Feel free to grab them too.

**Comment by marcmaceira** [comment]
Repository has been archived.
